### ISSUE TITLE
Bad strings hardcoded concatenation.

### ISSUE THREAD

**Issue by pedro-mendonca** [afragen/wordpress-beta-tester#12]
Currently there are a few new strings that concatenate like below:

- Currently your site is set to update to version **X.x.x**.
- Currently your site is set to update to version **next development version**. <-- issue
- Currently your site is set to update to version **X.x.x or X.x.x or X.x.x, whichever is released first**. <-- ' or ' missing gettext

Consider change to:
- Currently your site is set to update to **version X.x.x**.
- Currently your site is set to update to **next development version**.
- Currently your site is set to update to **version X.x.x, X.x.x and X.x.x, whichever is released first**. <-- using `wp_sprintf`

**Comment by afragen** [comment]
Thanks @pedro-mendonca. I'll take a look at this.
