### ISSUE TITLE
Add dashboard widget

### ISSUE THREAD

**Issue by afragen** [afragen/wordpress-beta-tester#14]
Idea from @azaozz, https://wordpress.slack.com/archives/C18723MQ8/p1582501567010100

Widget would display after a new beta/RC with link to _what to test_, likely form release post from make/core or commit messages from RSS.

**Comment by afragen** [comment]
First pass is something like the following.

<img width="614" alt="screenshot_57" src="https://user-images.githubusercontent.com/1296790/75202088-10761c00-571f-11ea-8f9d-9bf6d4309d27.png">

**Comment by afragen** [comment]
Simplify message to just call to action for testing. Link is to closed milestoned trac tickets.

<img width="609" alt="screenshot_58" src="https://user-images.githubusercontent.com/1296790/75204985-6222a480-5727-11ea-9fff-f4cff6a0dcb0.png">

**Comment by azaozz** [comment]
Yeah, thinking the above screenshot makes sense when the plugin is activated but the site is not on a "test" stream.

If it's going to link to https://wordpress.org/news/category/development/ the top line could probably be:

> Help test {post_title} released on {post_date}.

Perhaps followed by a short excerpt from the post?

If the site is on a testing stream, perhaps the message should be something like: 

> Your website was updated to WordPress version {wp_version} on {date/time}. The latest changes are outlined in {post_title}.

(Seems the info can be pulled from https://wordpress.org/news/category/development/feed/ relatively easily).

**Comment by afragen** [comment]
> Yeah, thinking the above screenshot makes sense when the plugin is activated but the site is not on a "test" stream.

If the plugin is active it will always be on a test stream.

`wp_widget_rss_output()` doesn't provide any parsing. 🙁

**Comment by afragen** [comment]
@azaozz I've got the following working. It will display the widget if the current WP version is `alpha|beta|RC`. Ping @pbiron

<img width="610" alt="screenshot_59" src="https://user-images.githubusercontent.com/1296790/75213497-24317a80-573f-11ea-9055-e5f00d96753f.png">

**Comment by pbiron** [comment]
just gave this a spin and it's great!!!

It should also add the widget to the `Network` dashboard in multisite.

In multisite, I think the widget should appear on the network dashboard and each site's dashboard as well, for maximum visibility.

**Comment by afragen** [comment]
https://github.com/afragen/wordpress-beta-tester/commit/78ba923c8492c9f9849bb7ed695667048b4d04e0
