### ISSUE TITLE
add a Help tab on the settings screen

### ISSUE THREAD

**Issue by pbiron** [afragen/wordpress-beta-tester#17]
We should add a Help tab on the settings screen that, among other things explains how the `Beta/RC` streams work (e.g., that you already have to have updated to a `nightly` before that option can be selected; and the confusion that might ensure if the trunk has already been branched).

We could probably explain that better in the readme as well.

see https://wordpress.org/support/topic/skips-version-5-4-rc1-and-jumps-to-5-5-alpha/

**Comment by afragen** [comment]
So a Help tab after the Extra Settings tab or a help tab in the something like a screen options dropdown? I'm assuming an extra tab.

**Comment by afragen** [comment]
The following is a start. https://github.com/afragen/wordpress-beta-tester/commit/40c70381300f7596c3176891e4db77fae464a07b
