### ISSUE TITLE
Not an error but a hint

### ISSUE THREAD

**Issue by La-Geek** [afragen/wordpress-beta-tester#18]
If I switch from Bleeding Edge or Beta/RC - Bleeding edge it to Point releases, I get an error message:

> “Error: Your current WordPress Beta Tester plugin configuration will downgrade your install to a previous version – please reconfigure it.”

But it is not really an error, since it is my decision to test a future minor release (of 5.3 atm). This should be (imo) “Hint: Your current …”

![Image 2020-03-09 at 7 26 44 PM](https://user-images.githubusercontent.com/1585416/76247859-85c60e80-6240-11ea-9d6f-3a1cd8f27a88.png)

**Comment by afragen** [comment]
It this better?

<img width="1251" alt="screenshot_65" src="https://user-images.githubusercontent.com/1296790/76248064-d23c2a80-61fd-11ea-9108-3ecf6be204ca.png">

**Comment by La-Geek** [comment]
It depends on ... :D

If it was a conscious decision to downgrade, resp. to test the upcoming minor (alpha/beta/rc) release a warning could be somehow confusing, here "hint" would be better.

But if Point release had been clicked out of ignorance, then "Warning" is exactly the right information.

Imo, someone who makes a conscious decision to downgrade, will be able to understand, that the warning is only a hint.

**Comment by afragen** [comment]
@La-Geek is there a notice type for a hint?

It seems that an error, current behavior, might be anxiety inducing. A warning is just that as sometimes a downgrade could cause a serious issue if the database changes.

**Comment by La-Geek** [comment]
Warning is okay I guess, this makes sense. Thank you for your time to solve this issue.
