### ISSUE TITLE
Replace the word beta with development

### ISSUE THREAD

**Issue by La-Geek** [afragen/wordpress-beta-tester#20]
https://build.trac.wordpress.org/browser/trunk/wp-admin/update-core.php?marks=264#L264
`This site is set up to install updates of future beta versions automatically.`

This message appears under Dashboard -> Updates after you have activated **Point release nightlies**
When you use the word beta it is very confusing, because that's often not true: alpha, beta and RCs are tested and nightly builds. This is not self-evident for beginners when they read that future beta versions are installed automatically. 

![2020-03-17_09h25_31](https://user-images.githubusercontent.com/1585416/76836558-4d6e9380-6831-11ea-8a3f-ef49a97cf4a6.jpg)

**Comment by afragen** [comment]
As this language is in WP core you would need to make a trac ticket with this request.

The term _beta_ used in this instance is more generic to testing an unreleased version of software. I don't believe there is any intent to reference any specific point in the development cycle -- development, alpha, beta, release candidate.

In this instance I believe the message is that you are not using the released version.
