### ISSUE TITLE
Array offset on a boolean

### ISSUE THREAD

**Issue by georgestephanis** [afragen/wordpress-beta-tester#21]
```
Notice: Trying to access array offset on value of type bool in /srv/users/userb1718256/apps/userb1718256/public/wp-content/plugins/wordpress-beta-tester/src/WPBT/WPBT_Bootstrap.php on line 128
```

It seems to happen sporadically, but something testing to make sure `$value` is an array before treating it as one here would probably remedy this:

https://github.com/afragen/wordpress-beta-tester/blob/eb776a4de891c586374e5f06cddc18070a7ce1e1/src/WPBT/WPBT_Bootstrap.php#L128

**Comment by afragen** [comment]
Hey George! Interesting that I've never seen this error but it's certainly easy enough to mitigate as suggested.

Thanks for the report.

**Comment by georgestephanis** [comment]
I'd tried to get a backtrace summary on it, but couldn't duplicate it properly so *shrug*

It is just a notice and not a warning, so I'm not surprised it doesn't crop up often.

**Comment by afragen** [comment]
I don't think I've ever seen it.
