### ISSUE TITLE
incorrect "next versions" displayed when running an RC vesion

### ISSUE THREAD

**Issue by pbiron** [afragen/wordpress-beta-tester#24]
Running WP 5.6-RC1 & Beta Tester 3.0.4, with `channel === Bleeding Edge` and `stream === Beta/RC Only`, I see the following:

> Currently your site is set to update to version 5.6-beta1, 5.6-RC2, or 5.6, whichever is released first.

The `5.6-beta1` should NOT be displayed there (and previously wasn't).

Not sure whether the fix should done be `WPBT_Core::get_next_version()` or in `WPBT_Core::calculate_next_versions()`.

**Comment by afragen** [comment]
I saw that too and I think the fix is to remove the beta element if the RC > 1

**Comment by pbiron** [comment]
yea, that's the fix...but where's the best place to do that was what I was getting at above.

**Comment by pbiron** [comment]
another fix would be to remove the beta element if `$wp_version` is any RC
