### ISSUE TITLE
http://nawabdera.Wordpress.com

### ISSUE THREAD

**Issue by NAWABDERA1** [afragen/wordpress-beta-tester#30]
http://nawabdera.Wordpress.com

**Comment by afragen** [comment]
What am I supposed to see here? If you have an actual issue please let me know what it is and not just leave a URL to somewhere.

**Comment by NAWABDERA1** [comment]
Thank you indeed 
My website is missing 
https://nawabdera.Wordpress.com 
I tried my best to reach Microsoft's help but in vain 
Similarly i can't connect to the iTunes through iPhone 13 pro max and iPad Pro 
https://social.microsoft.com/Profile/nawabdera 
thank you again 
Regards 
Nawab IkramUllah khan nawabdera
