### ISSUE TITLE
PHP 8.1: Deprecated: explode()

### ISSUE THREAD

**Issue by Soean** [afragen/wordpress-beta-tester#33]
`get_current_wp_release()` returns `null`, if the API responds with an error:

https://github.com/afragen/wordpress-beta-tester/blob/d6510bf85f6f4323188a11ccd8d1edd4f49a3154/src/WPBT/WP_Beta_Tester.php#L240-L242

This value is used as 2. parameter in `explode()`:
```php
$current_release        = $this->wp_beta_tester->get_current_wp_release();
$next_release           = array_map( 'intval', explode( '.', $current_release ) );
```

With PHP 8.1 I get an error:
`Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated`

**Comment by afragen** [comment]
Thanks for the debugging. I'll get this updated and released.

**Comment by afragen** [comment]
Fixed. https://github.com/afragen/wordpress-beta-tester/commit/b28a5fbfe1f05151eac0f68f316f5ed568252165
