### ISSUE TITLE
Possible wrong punctuation mark in a string.

### ISSUE THREAD

**Issue by NekoJonez** [afragen/wordpress-beta-tester#35]
In my honest opinion, the string:

"`Why don&#8217;t you <a href="update-core.php">head on over and upgrade now</a>.`" sounds like a question and shouldn't end in a "." but a "?". I have a PR for this: #34

**Comment by afragen** [comment]
I don't disagree, but I think it's a point where text and voice are confusing. It's the same language for a long time. I interpret it as "you should go update" not "do you want to update". 

Perhaps changing it to a more declarative statement would be better Maybe something like,

`Perhaps you should head on over and upgrade now.`, obviously with link.

**Comment by NekoJonez** [comment]
I will adjust my PR tomorrow. My mind is mush right now from a long workday

**Comment by NekoJonez** [comment]
@afragen Sorry for the long silence. It's soon an open day at the school I work for and I only now got the time to update the PR.

**Comment by pbiron** [comment]
I didn't right the original string.   But rather than being a true question it's more like a "request/command" stated as a question.  It's kind of "passive aggressive", but given my sense of humor, I kind of like it the way it is ::grin::  But won't object to a change.
