### ISSUE TITLE
Safari version used in "Report a Bug" feature could be confusing

### ISSUE THREAD

**Issue by ironprogrammer** [afragen/wordpress-beta-tester#37]
In macOS, the new [Report a Bug](https://github.com/afragen/wordpress-beta-tester/pull/36) feature emits the `Safari/x.x.x` version found in  the `User-Agent` string, but the Safari app itself reports the version from `Version/x.x.x` 🙃 (I did not test this behavior in Windows.)

For instance, given the following UA:
```
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15
```

The scraped Safari version is:
<img width="275" alt="Report a Bug environment info" src="https://user-images.githubusercontent.com/824344/225700128-83ac56ea-3697-43ed-bade-88857a05662f.png">

Compare this with the version reported in Safari's About... menu:
<img width="286" alt="Safari About dialog" src="https://user-images.githubusercontent.com/824344/225700259-99fb8bff-7ed0-462f-90e6-77d1cdd459d6.png">

It would be less confusing for the Report a Bug feature to use the same version reported in Safari's UI.

**Comment by ipajen** [comment]
Same problem on iOS safari

Mozilla/5.0 (iPhone; CPU iPhone OS 16_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Mobile/15E148 Safari/604.1

version 16.3 shows as - Browser: Safari 604.1 (Mobile)

**Comment by afragen** [comment]
As near as I can tell the version 16.3 corresponds to the OS version of the Safari release. I'm assuming the 604.1 is a more accurate version of the application.

**Comment by ipajen** [comment]
@afragen  According to https://www.whatsmyua.info/ [ua-parser-js](https://github.com/faisalman/ua-parser-js) and [platform.js](https://github.com/bestiejs/platform.js/) the browser version is safari 16.3 and IOS version 16.3.1 and Version history from apple on https://developer.apple.com/documentation/safari-release-notes on my user string. Not sure if the 15E148 is the build number

**Comment by afragen** [comment]
But that's not in the User-Agent header, is it?
