### ISSUE TITLE
"Report a Bug" shown in admin-bar for none admin users

### ISSUE THREAD

**Issue by ipajen** [afragen/wordpress-beta-tester#38]
If a user for example contributor clicks on the link "Report a Bug" in top wp-admin bar they will get   "Sorry, you are not allowed to access this page."

If the user don't have correct access, it would be preferred that the "Report a Bug" is not shown in the top admin bar meny

**Comment by afragen** [comment]
What role does your user have that this occurs?

**Comment by ipajen** [comment]
@afragen contributor
