### ISSUE TITLE
"Report a Bug"  Browser Edge not showing version in Environment

### ISSUE THREAD

**Issue by ipajen** [afragen/wordpress-beta-tester#41]
User string:

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.69

Is not showing version only browser. 

=== Environment
- Browser: Edge

**Comment by afragen** [comment]
Should be fixed now in develop
