### ISSUE TITLE
Query Monitor usage shows database error 

### ISSUE THREAD

**Issue by ipajen** [afragen/wordpress-beta-tester#62]
### Bug Report
When using Query Monitor and going to Wordpress Dashboard  there is a database error notice. If WordPress beta tester is inactive there is no notice. 

### Environment
- WordPress: 6.2-RC2
- PHP: 8.1.16
- Server: LiteSpeed
- Database: mysqli (Server: 10.4.28-MariaDB / Client: 10.4.28-MariaDB)
- Browser: Edge 111.0.1661.44 (Windows 10/11)
- Theme: Twenty Twenty-Three 1.1
- MU-Plugins: 
  * WordPress automation by Installatron 
- Plugins: 
  * Code Snippets 3.3.0
  * Git Updater 12.1.2.3
  * Query Monitor 3.12.0
  * WordPress Beta Tester 3.3.2.1
  * WP SMS 6.1.1

### Steps to Reproduce
1. Use Query Monitor plugin and have WordPress Beta Tester active
2. Go to "/wp-admin/index.php"
3. 🐞 Bug occurs.

### Expected Results
1.  ✅ No Error

### Actual Results
1.  ❌ Error Shows in Query Monitor,  But no error message is given.

Is this something in WordPress beta tester or is it a problem in query monitor as a false positive as no error message is given?

```
DELETE
FROM `wp_options`
WHERE `option_name` = '_transient_timeout_feed_mod_063c3a22b3af6d27076b025e59f22d9f'
```
```
add_option()
wp-includes/option.php:680
set_transient('feed_063c3a22b3af6d27076b025e59f22d9f')
wp-includes/option.php:988
WP_Feed_Cache_Transient->save()
wp-includes/class-wp-feed-cache-transient.php:83
SimplePie->init()
wp-includes/class-simplepie.php:1562
fetch_feed()
wp-includes/feed.php:829
wp_widget_rss_output()
wp-includes/widgets.php:1571
WP_Beta_Tester->parse_development_feed()
wp-content/plugins/wordpress-beta-tester/src/WPBT/WP_Beta_Tester.php:335
WP_Beta_Tester->beta_tester_dashboard()
wp-content/plugins/wordpress-beta-tester/src/WPBT/WP_Beta_Tester.php:303
do_meta_boxes()
wp-admin/includes/template.php:1445
wp_dashboard()
wp-admin/includes/dashboard.php:271
```

**Comment by afragen** [comment]
Hmm, I have QM active in all my testing sites, including the sites testing Beta Tester. I have not encountered this issue. 

```
=== Environment
- WordPress: 6.2-RC2-55551
- PHP: 8.1.9
- Server: nginx/1.16.0
- Database: mysqli (Server: 8.0.16 / Client: mysqlnd 8.1.9)
- Browser: Safari 16.3 (macOS)
- Theme: Frost 0.9.10
```

**Comment by pbiron** [comment]
I haven't been able to replicate this problem either and I use QM on all sites.

**Comment by ipajen** [comment]
I have opened a support ticket at QM https://wordpress.org/support/topic/database-error-with-no-error-message/ for investigation if it’s a false one.
