### ISSUE TITLE
Add ability to update to "next" beta/RC packages and not just nightlies

### ISSUE THREAD

**Issue by pbiron** [afragen/wordpress-beta-tester#7]
I've created a repo for my plugin that limits updates to the next beta/RC packages.  You can get it from https://github.com/pbiron/shc-wordpress-beta-tester.

There are notes in the readme and inline in the code with my thoughts on how that functionality might be incorporated in `WordPress Beta Tester`.

**Comment by afragen** [comment]
I've taken a quick look at the code.

What I envision is a _dropin_ class **Beta_RC** and another radio button choice on the main Beta Tester page. 

Hopefully I can make the logic pick up the current bleeding edge or point release and only pick the correct package depending upon where the user started. Not certain if this will become confusing and maybe 2 choices will be needed.

**Comment by afragen** [comment]
When ready you can make a PR against the `beta-rc` branch.

**Comment by pbiron** [comment]
> What I envision is a _dropin_ class **Beta_RC** and another radio button choice on the main Beta Tester page.

That's basically what I've been thinking of too.

> Hopefully I can make the logic pick up the current bleeding edge or point release and only pick the correct package depending upon where the user started.

I haven't done any testing with `point release` because I didn't put my plugin together until `5.3-beta1` was released.

> Not certain if this will become confusing and maybe 2 choices will be needed.

 Yeah, I haven't thought thru exactly what the UX for the settings would be.  I'll play around with it and see what I can come up with.

**Comment by afragen** [comment]
Currently there is a single `Beta/RC` choice and it defaults to whatever your previously current branch was. In order to switch you would need to select either `point release` or `bleeding edge`, save, then update to that branch from `core-update.php`. The selecting `Beta/RC` would be based on the branch.

**Comment by afragen** [comment]
I think we might need to save the beta/RC package once generated so that we can return it with a simple `getter`. Then we can easily insert it into `WP_Beta_Tester::get_preferred_from_update_core()`
