### ISSUE TITLE
Copy to clipboard “report a bug”

### ISSUE THREAD

**Issue by ipajen** [afragen/wordpress-beta-tester#70]
Copy to clipboard and then past looks like this:

earlier version didn’t do this tab when pasting, is it a bug or new feature?

		## Bug Report
		### Description
		Describe the bug.

		### Environment
		- WordPress: 6.2-RC4
- PHP: 8.2.3
- Server: LiteSpeed
- Database: mysqli (Server: 10.4.28-MariaDB / Client: mysqlnd 8.2.3)
- Browser: Safari 16.3 (Mobile) (iPhone)
- Theme: GeneratePress 3.3.0
- MU-Plugins: 
  * WordPress automation by Installatron 
- Plugins: 
  * Advanced Database Cleaner 3.1.2
  * All-in-One WP Migration 7.72
  * Code Snippets 3.3.0
  * Git Updater 12.1.3
  * GP Premium 2.3.0
  * Query Monitor 3.12.1
  * WordPress Beta Tester 3.3.5
  * WP Crontrol 1.15.2
  * WP SMS 6.1.2

		### Steps to Reproduce
		1. 
		2. 🐞 Bug occurs.

		### Expected Results
		1.  ✅ What should happen.

		### Actual Results
		1.  ❌ What actually happened.

**Comment by afragen** [comment]
oops.

**Comment by afragen** [comment]
Just released a fix.
