### ISSUE TITLE
Undefined property notice when using SQLite

### ISSUE THREAD

**Issue by ironprogrammer** [afragen/wordpress-beta-tester#71]
When running [WordPress on SQLite](https://github.com/aaemnnosttv/wp-sqlite-db), the following notice is logged when viewing the "Report a Bug" tab:

`Notice: Undefined property: WP_SQLite_DB\PDOEngine::$client_info in ../WPBT_Bug_Report.php on line 282`

The output for the bug template reflects the following database info:
```
- Database: WP_SQLite_DB\PDOEngine (Server: 5.5 / Client: )
```

(I haven't tested this with the "official" [SQLite canonical plugin](https://wordpress.org/plugins/sqlite-database-integration/), but it's based on the same code as linked above.)

Tested using WPBT 3.3.6.

**Comment by pbiron** [comment]
thanx for the report.  Can you please check what Site Health displays in it's Info > Database section?

**Comment by costdev** [comment]
@ironprogrammer Thanks for the report! Can you also check the value of `PDO::ATTR_SERVER_VERSION` and `PDO::ATTR_CLIENT_VERSION` and let us know what they show? [Ref](https://www.php.net/manual/en/pdo.constants.php)
