### ISSUE TITLE
Warning in a site running WP 6.7 beta1

### ISSUE THREAD

**Issue by mrleemon** [afragen/wordpress-beta-tester#79]
### Description
Using the plugin in a WordPress site running WP 6.7 beta1 throws the following warning:

`Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the wordpress-beta-tester domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in xxxxxx\wp-includes\functions.php on line 6099`

### Environment
- WordPress: 6.7-beta1
- PHP: 8.1.23
- Server: nginx/1.16.0
- Database: mysqli (Server: 8.0.16 / Client: mysqlnd 8.1.23)
- Browser: Firefox 130.0 (Windows 10/11)
- Theme: Horizontalee 3.0
- MU-Plugins: None
- Plugins: 
  * WordPress Beta Tester 3.5.6

### Steps to Reproduce
1. Install WordPress Beta Tester plugin in a site running WP 6.7 beta1
2. Add `define( 'WP_DEBUG', true );` to the `wp-config.php` file
3. 🐞 Bug occurs.

### Expected Results
1.  ✅ What should happen.

### Actual Results
1.  ❌ What actually happened.

**Comment by afragen** [comment]
Thanks for the report. I've been seeing that a lot too.

**Comment by afragen** [comment]
I don’t think core wants us to specifically load the text domain any longer.

**Comment by afragen** [comment]
I think this was because of something in the Report a Bug feature. I've removed the feature in favor of simply using the standalone Test Reports plugin available in my GitHub or in the .org repo.
