### ISSUE TITLE
Remove `load_plugin_textdomain` call

### ISSUE THREAD

**Issue by swissspidy** [afragen/wordpress-beta-tester#80]
It doesn't do anything anymore really, WordPress can load translations just-in-time. No point in having this call, it can be simply removed :)

**Comment by afragen** [comment]
I'm trying to maintain the longest compatibility for the Beta Tester plugin and this would cut translations off at WP 4.6 I think.

**Comment by swissspidy** [comment]
Yes indeed it would. Didn't realize this still supports all the way to 3.1, in that case should be fine to keep it 😄
