### ISSUE TITLE
WP 6.7: Inadvertently loading translations too early

### ISSUE THREAD

**Issue by swissspidy** [afragen/wordpress-beta-tester#81]
The plugin triggers just-in-time translation loading too early, before any other plugins are loaded, and before the current user is properly set up and things like locale switching are possible.

Backtrace:

1. `WPBT_Bootstrap->run()` call in main plugin file
2. That method calls `WP_Beta_Tester->run()`
3. That method then calls `WPBT_Settings->run()`
4. That method then calls `new WPBT_Bug_Report()`
5. `WPBT_Bug_Report::__construct()` calls `__()`
6. That triggers translations to be loaded

There's really no need for those strings to be defined as static class properties in `WPBT_Bug_Report::__constrct()`. If you remove those calls and just use the strings later when you actually need them, this issue goes away.

**Comment by afragen** [comment]
Thanks. I've removed the Report a Bug feature that seems to have the issue in favor of using the standalone Test Reports plugin in the .org repo.
